### ISSUE TITLE
Possible to change Engie Hud Placement?

### ISSUE THREAD

**Issue by TWYSTDMMIND** [Sevin7/7HUD#28]
As of right now on the left side, it interferes with the Middle and Bottom basechat.res. Is it possible to move it over to the right side? 

![](http://i.imgur.com/JV1qXJv.jpg)

![2014-09-16_00002](https://cloud.githubusercontent.com/assets/6333092/4290140/3b25d132-3db9-11e4-8c7e-574479591ad7.jpg)

![2014-09-16_00004](https://cloud.githubusercontent.com/assets/6333092/4290144/42f7ad40-3db9-11e4-9025-323e389a040d.jpg)

**Comment by Sevin7** [comment]
Going to be adding readme instructions for manually moving the engineer panel in v4.61. It is not feasible to code positioning into 4Plug as the position is dictated by an entry in hudlayout, which would require me to make several more hudlayout copies. There are already 3 of those copies, I don't want to keep populating the HUD with more as it's simple enough to fix manually.
