### ISSUE TITLE
text cut off on various screens 

### ISSUE THREAD

**Issue by 1112e** [Sevin7/7HUD#35]
![](http://i.imgur.com/NSX06Wh.png)

**Comment by Sevin7** [comment]
I think those are caused by the font I'm using, though that seems odd since
Futura is a very commonly used font family. I've just been ignoring them
since you can still read everything just fine, but it is rather ugly.

**Comment by 1112e** [comment]
I'll mess around with some different fonts and see how that looks

**Comment by 1112e** [comment]
I changed it to roboto light, and it doesn't cut off. 
![](http://i.imgur.com/jGpfTxW.png)

**Comment by 1112e** [comment]
The only thing I could think of to fix it while keeping the same font is changing the size of the container that holds the game tips

**Comment by Sevin7** [comment]
So it is a font issue. I imagined so, unfortunate that Futura has that
issue. Perhaps it's because it's an OTF? Roboto looks nice, you should hit
me up with the download to that :)

**Comment by 1112e** [comment]
https://www.google.com/fonts/specimen/Roboto

**Comment by 1112e** [comment]
Here's where you download it https://www.google.com/fonts#UsePlace:use/Collection:Roboto

**Comment by Sevin7** [comment]
I'll test out replacing Futura with Roboto. Thanks dude.

**Comment by 1112e** [comment]
No problem

**Comment by Sevin7** [comment]
Roboto looks a bit out of place to me in 7HUD. Messed around a bit with
some other variants and different fonts as well, can't find something I
like yet. I'll work on out. Futura is out for v4.13.
