### ISSUE TITLE
Invisible Items on Class Selection Menu

### ISSUE THREAD

**Issue by Heyo99** [Sevin7/7HUD#41]
So this has been the reason I haven't been using 7HUD recently. So is this a problem for everyone?

**Comment by Sevin7** [comment]
Can you provide a screenshot? I believe I fixed this for the next version.

**Comment by elomatreb** [comment]
I think this is referencing this:

![2015-07-11_00001](https://cloud.githubusercontent.com/assets/3387265/8633782/c78ef11e-27db-11e5-8a66-7a776fb73685.jpg)

As you can see, the weapon model is nearly invisible on the class selection screen. But I do not think that this is a bug in this HUD, but rather in the game itself. I was using flathud and rayshud earlier, noticed the same thing.

**Comment by Sevin7** [comment]
I don't have this issue, but it may be fixed in the next version for those
who do.
