### ISSUE TITLE
mp_tournament_readymode 1

### ISSUE THREAD

**Issue by averagecomputerguy** [Sevin7/7HUD#42]
![image](https://cloud.githubusercontent.com/assets/3173124/9138164/c30dd26a-3ce7-11e5-9453-968e1f343e85.png)

When the cvar in the title is set on a server, the hud looks like this with the user's box in an awkward position. It'd be nice if you could fix it. :)

thx in advance

**Comment by Sevin7** [comment]
Should be good with v4.21.
