### ISSUE TITLE
Player health too low on screen

### ISSUE THREAD

**Issue by jzhu98** [Sevin7/7HUD#43]
Greetings, Sevin7,

I updated my version of 7HUD recently and I saw this:

![rsz_1screenshot_from_2015-11-29_12-02-04](https://cloud.githubusercontent.com/assets/2917145/11459020/c87b5506-9692-11e5-8325-1fa8445c8a8f.png)

I ran a `git blame` on the relevant file `resources/ui/HudPlayerHealth.res` and I found this diff from the commit c6d00b8 that seems to have caused the problem:

`line 63`
```diff
diff --git a/resource/ui/HudPlayerHealth.res b/resource/ui/HudPlayerHealth.res
index 6e36498..19b4ee8 100755
--- a/resource/ui/HudPlayerHealth.res
+++ b/resource/ui/HudPlayerHealth.res
@@ -60,7 +60,7 @@
-		"ypos"			"r281"
+		"ypos"			"r211"
```

Reverting this change fixed the problem.

I suspect this may be a platform-specific bug, as I'm running Linux.

Here's my system specs:
Arch Linux (rolling release)
T430 Thinkpad (i5-3210M / Intel Graphics HD 4000)
OpenGL 3.0 (core profile OpenGL 3.3), using the Mesa3D implementation

TF2 `version` output (running the latest TF2)
Client version:        3141841
Build Label:           3142994   # Uniquely identifies each build
Client AppID:              440
Network PatchVersion:  3141841   # Determines client and server compatibility
Protocol version:           24   # High level network protocol version
Server version:        3142994
Server AppID:           232250

The only other things in my custom folder are a quake hitsound and my keyboard binds. I've got a crosshair switcher (from clugu.com/tf2mate) but there's no custom HUD elements in it.

Feel free to pester me for any other information.

**Comment by Sevin7** [comment]
Thanks for the report. I must have accidentally applied an adjustment to
the wrong file since I have a lowered and centered version of the HUD. I've
done this before. Will be fixed shortly.

**Comment by Sevin7** [comment]
Fixed.
