### ISSUE TITLE
Should "On the bright side..." feature work with 7HUD?

### ISSUE THREAD

**Issue by jeremyclarke** [Sevin7/7HUD#50]
Basically I restarted playing TF2 after many years about a year ago. I've become a WAY better player (no more W+M1) and I've been using 7HUD for most of this "golden age" (e.g. during which I racked up dozens of achievements I didn't have before). 

The thing is I haven't seen an "on the bright side... [you killed more people as demoman this round than your previous best]" message in this entire time, at least not since the era when I was still using the stock  HUD. 

SO: Should it be working? Do you expect it to be disabled/hidden based on the code you already have?

IF ITS INTENTIONAL: Can you recommend the code I need to change to re-enable it? 

I'd be okay if it 'looked wrong' as long as I could see the message. I love these little micro-records and they contain data that I can't seem to find anywhere else in the TF2/Steam UI. 

Thanks for any feedback.

**Comment by Sevin7** [comment]
I believe this was already removed from the yA_HUD base I started with. You
can re-enable it by putting in the default values for the "StatPanel"
section in hudlayout.res.

**Comment by jeremyclarke** [comment]
THANK YOU! I found the definition and here is an alteration that makes the panel visible for me: 
```
StatPanel
	{
		"fieldName"			"StatPanel"
		"visible"				"1"
		"enabled"				"1"
		"xpos"				"200"
		"ypos"				"200"
		"wide"				"f0"
		"tall"				"480"
	}
```

I wish TF2 had an advanced option to enable/disable this so HUDs didn't have to force it on or off. Personally I think the default should be to keep it on unless a user asks to have it removed.

**Comment by Sevin7** [comment]
Glad you found it. I think it's a pretty minor thing, so they wouldn't have
an option for something that doesn't get seen very much anyway.

**Comment by jeremyclarke** [comment]
Would you consider re-instating the feature in 7HUD? If it's minor then that wouldn't be a problem ;)

The issue IMHO (and from reading about it trying to find a solution) is that a lot of serious players find it annoying because it will show up a lot for boring stats like "your 1 domination is almost as much as your 2 domination record" with very few about your more interesting records that you almost never even come close to. This leads to people wanting it disabled completely, and HUDs that disable it for those users without any kind of configuration option to make it work again. 

If core TF2 had an option then HUDs could just design the message to match the HUD and let the setting control whether it shows. Until then HUDs have to make the decision on player's behalf. 

I'd rather it be visible and the FAQ tells you what to edit to hide it, but I can see it both ways and it's up to you. If you keep it disabled by default then a note in the FAQ/readme about how to enable it would be nice. 

---

Separately: Do you know where I could put this in my custom cfg scripts so that I can control it on my end without having my edits in the 7HUD directory? I have it as an uncommitted change in Git right now (and pulling updates should work fine most of the time when that file isn't edited), but it would be nice to have everything compartmentalized.

**Comment by Sevin7** [comment]
You're right, most people find it annoying as 90% of the time it shows up it's to  tell you something that you don't care about. Also as you've said, you never even noticed it was gone in the year you've been using my HUD. This is just a testament being an extremely minor change. 

Because the code for the element is in hudlayout.res, coding this as an option in 4Plug is impossible. There are so many other elements controlled in hudlayout that I already have multiple copies of it swap  in depending on the options you choose in hudlayout. I'd have to double that count to add this little text in.

This kind of thing is also impossible to setup in scripts.

I will consider adding it back in redesigned, but again, 90% of the time it's pretty useless so I may not.

**Comment by jeremyclarke** [comment]
Great, thanks so much for considering it either way. 

Too bad it's unscriptable, that's what I would have done. Haven't used 4plug yet because it doesn't seem worth the hassle on OSX. 

FWIW I did notice it was gone, just took me a long time beause it's so easy to forget about it. I should have clued in when I was doing off-class contracts, I bet it would have improved that slog :P

A redesign that made the box smaller/prettier/easier-to-ignore would be pretty sweet :)

Thanks for all your work!
