### ISSUE TITLE
Opening scoreboard causes brief, severe frame drops

### ISSUE THREAD

**Issue by pabp** [Sevin7/7HUD#51]
As the title says, opening the scoreboard with Tab causes the framerate to crash to single digits for a split second. Here's a recording of it happening, https://gfycat.com/PreciousQuickHummingbird. The first time I open the scoreboard, the minimum FPS drops from 91 to 8 and the game visibly stutters. The video is just as it happened in game, no edits aside from zooming on the FPS counter.

**Comment by Sevin7** [comment]
This has been happening to everyone, it's a Valve issue.
