### ISSUE TITLE
edit class crashes

### ISSUE THREAD

**Issue by sedflanbird** [Sevin7/7HUD#52]
the edit class key is broken. When I press e to edit a class the game crashes to desktop. And often the "edit class" text will disappear.

example: http://puu.sh/ozxMV/471764b292.jpg

**Comment by Sevin7** [comment]
Have you updated to the latest version? My edit class text is always
visible and I don't crash.

**Comment by sedflanbird** [comment]
updated from the website again just to make sure. played a round of dustbowl and the text disappeared but the game didn't crash when I used the hotkey. Jumped to a 2fort server and used the hotkey and the game crashed to desktop.

**Comment by Sevin7** [comment]
That sure is weird. Perhaps the edit loadout command is causing issues?
Doesn't really sound like something that would be HUD related if it's
intermittent. Try using the edit loadout button in the default HUD.

**Comment by sedflanbird** [comment]
Alright I checked out some other hud and the text disappears when highlighting over random with this one as well (and im just going to assume the crash is going to still happen.) Do you have any idea on why this might be happening?

**Comment by Sevin7** [comment]
Like I said, probably a Valve issue.
