### ISSUE TITLE
Scoreboard elements from MvM are in normal game and vice versa

### ISSUE THREAD

**Issue by cineafx** [Sevin7/7HUD#54]
The numbers that are only suppose to be visible in MvM are still visible in the normal game and vice versa. 
http://imgur.com/a/HwgY9

**Comment by cineafx** [comment]
This only happends if you join a MvM server prior to playing a normal gamemode or a normal gamemode prior to playing MvM.

**Comment by Sevin7** [comment]
Fixed in v4.47.
