### ISSUE TITLE
Mousewheel/prev item/next item breaks on mac when 7HUD enabled

### ISSUE THREAD

**Issue by jeremyclarke** [Sevin7/7HUD#55]
Hi and thanks as always for the great hud and it's mac support!

I've been driven crazy lately by my inability to use the mouse wheel to switch weapons up and down. I though it was my custom configs so I disabled them and reset all keys but still it didn't work. I then tried disabling everything including 7HUD and it worked again. Re-enabling 7HUD only broke it, so I'm pretty sure it's the culprit. 

Some notes:
- I can use the scroll wheel exactly once and it seems to do what I expect.
- After the switch it makes a noise though and strangely the noise I hear is very specifically a Half Life sound, the sound like "_brup_" you hear when using the weapon menus in HL and which makes me think of crowbars. 
- Further use of the scroll wheel within a game just makes the same _brup_ noise with no effect at all.
- Opening a fresh game (disconnect+reconnect/create) resets this, and I get my single instance of it working+brup before failing again for further use.

Weapon prev/next is the default behavior of the scroll wheel, but I don't think the mouse is the actual problem. I tried setting the "previous weapon" and "next weapon" commands in keyboard settings to "r" and "t" and found that it had the same effect as the mouse wheel: 
- First press switches weapon and _brup_
- Subsequent presses make _brup_ sound and nothing happens. 

I imagine this is somehow mac specific because otherwise someone would have noticed, but maybe people don't use the scroll wheel as much as me?

Thanks for looking into it if you can!

**Comment by jeremyclarke** [comment]
FWIW I just tried Toonhud and budhud and both had the same issue!

Could be something in core TF2 causing it, still if you have any ideas about how to fix it I'm very eager.

**Comment by Sevin7** [comment]
That's weird, never heard of that issue. Valve and TF2 are not perfect, there tend to be things that get broken in custom HUDs just because of how the game is coded I guess. 

I don't use next/prev weapon keys, I have slot1 bound to mwheelup and slot3 bound to mwheeldown for most classes.
