### ISSUE TITLE
Weird box appearing at the top of screen not allowing weapon switching

### ISSUE THREAD

**Issue by haascunt** [Sevin7/7HUD#57]
Hi I recently installed your HUD and loved it but today when I launched TF2 and joined a game there was a weird box that had the letters "A B C D" with the word equipped and a scroll bar. I don't know if this is directly causing this other issue but i'm also not allowed to switch weapons using the number keys.

**Comment by Sevin7** [comment]
I've heard reports of this recently, still trying to figure out the cause. Sit tight.

**Comment by foobark** [comment]
FWIW I have the black box too, it disappears if I toggle scoreboards (to 9v9). Dunno about weapon switching, don't use the number keys for that.

**Comment by haascunt** [comment]
@foobark How would I go about toggling scoreboards to 12v12

**Comment by Sevin7** [comment]
There's a scoreboard button on the menu.

**Comment by AlessioScarlet** [comment]
same problem here.

**Comment by L4mpshade** [comment]
I had the same problem and fixed it by disabling minimal HUD in the advanced options.

**Comment by AMACB** [comment]
@L4mpshade That fixed it for me! Thanks!

**Comment by Sevin7** [comment]
I think I solved this issue with v4.60.
