### ISSUE TITLE
Problems.

### ISSUE THREAD

**Issue by 23SRLITheGamer** [Sevin7/7HUD#62]
So when I'm in game, whenever I get killed this weird black thing consumes my screen not showing me the guy that killed me. Also when I started using this hud, my game seems to lag more than it used to.
Can some1 help me?

**Comment by Sevin7** [comment]
"This weird black thing"? Can you give me a screenshot? As for your lag,
HUDs have very little impact on FPS.

**Comment by Sevin7** [comment]
That's normal. That happens to any custom HUD that doesn't use the base background.

**Comment by 23SRLITheGamer** [comment]
Ok. Thank you! :)

**Comment by Sevin7** [comment]
You're welcome :)
