### ISSUE TITLE
More Problems

### ISSUE THREAD

**Issue by 23SRLITheGamer** [Sevin7/7HUD#63]
here's one
![1](https://cloud.githubusercontent.com/assets/16334980/19189814/8547c91e-8ccc-11e6-9ee4-37f0824a571c.jpg)
and also I don't know why but when I use your hud my keys seems to get unbinded and messes up my game

**Comment by 23SRLITheGamer** [comment]
the problem is in the upper right corner

**Comment by Sevin7** [comment]
Yeah, that's normal. The notification icon doesn't always show. To keep your keys bound, you should use the autoexec.cfg. Sometimes key an mouse bindings don't get saved, it's not necessarily a HUD thing.
