### ISSUE TITLE
Use default loading screens background?

### ISSUE THREAD

**Issue by pietchaki** [Sevin7/7HUD#67]
Would it be possible to use the original backgrounds in map loading screens?
Or custom images for each official map?

**Comment by Sevin7** [comment]
Yes, just delete the materials folder. That will get rid of the backgrounds and add the stock characters back in. Custom backgrounds will come in a materials folder if you want to install other ones yourself.
		

		
	





On Fri, May 26, 2017 at 7:38 PM -0400, "pietchaki" <notifications@github.com> wrote:












Would it be possible to use the original backgrounds in map loading screens?

Or custom images for each official map?
