### ISSUE TITLE
Download from site does not load due to capitalization.

### ISSUE THREAD

**Issue by SylveonBottle** [Sevin7/7HUD#69]
http://sevin7.github.io/7HUD/

Downloading 7HUD from there gives you a file to put in your custom folder called "7HUD"
TF2 does not load folders in tf/custom properly if they have capital letters in them.

Solution is to rename 7HUD to 7hud.

**Comment by Sevin7** [comment]
TF2 does read capitalized folders. Mine is called "7HUD" and it works fine.

**Comment by SylveonBottle** [comment]
Sorry, I suppose I should have mentioned that I'm on ArchLinux. This may have to do with the fact that TF2 reads/writes files just a tad bit differently on Linux.

The simple patch would just remove capitalization. Capitalization is of no importance when it completely breaks the pack for some users. If they really must, users could simply rename it from "7hud" to "7HUD" if it makes such a big deal for them.

I wonder how many users decided to not try this pack because they did not attempt to rename the folder to lower-case. I only did it because I noticed steam kept creating a new folder in tf/custom called "7hud", with a sounds file in it. I figured that TF2 was improperly loading the files, renamed 7HUD to 7hud, and it worked like a charm. No other edits made to the pack.

If you *really* hate the idea of lower-casing the folder, could you at least add to the README.md about this bug for linux users, and how to fix it?

**Comment by IdleGandalf** [comment]
If you are on linux why dont you try a git clone? Its simpler and much easier to update. Besides, I'm on Arch as well, git clone folder is named 7HUD and it works perfectly fine.

**Comment by Sevin7** [comment]
It's not a big deal. I will lowercase the folder next update.
