### ISSUE TITLE
[LINUX] 12v12 Scoreboard clipping issues at 1440p

### ISSUE THREAD

**Issue by Duptier** [Sevin7/7hud#84]
Any fresh install of 7HUD with 12v12 scoreboard leads to clipping shown below:

![20220118144240_1](https://user-images.githubusercontent.com/82429716/149872371-afbf9437-b95c-4f5b-8eed-09286ee1e2e0.jpg)

Through my testing, this issue does not occur at 1080p:

![20220118144303_1](https://user-images.githubusercontent.com/82429716/149872373-eb389e9c-d98d-4c6b-9b0d-dfdadbbe6223.jpg)

So far, I have only tested this with the Linux version of TF2.

The only changes I made to the hud was changing the angles and sizes of hudplayerclass.res.

**Comment by Sevin7** [comment]
What clipping are you referring to? I'm not seeing anything wrong with either image, maybe I'm missing something.

**Comment by Duptier** [comment]
In the 1440p image, the score area which shows the player score and name clips into the team titlebar

**Comment by Sevin7** [comment]
Some elements shift slightly at different resolutions. I can't make them all cooperate, unfortunately.

**Comment by Duptier** [comment]
Fair enough. It is only a minor issue, after all.
