### ISSUE TITLE
[LINUX] Vaccinator charge meter in the wrong position

### ISSUE THREAD

**Issue by Duptier** [Sevin7/7hud#85]
When playing as Vaccinator Medic, the charge meter for the Vaccinator appears over the top of the charge percent text:

![20220118145547_1](https://user-images.githubusercontent.com/82429716/149873452-79a0e14e-723c-4a4b-8086-1bc3a512cf1a.jpg)

From my testing, this issue occurs at both 1440p and 1080p

This issue does not occur with the other mediguns:

![20220118145555_1](https://user-images.githubusercontent.com/82429716/149873506-b5f17970-d85a-4fc4-80fe-602d113552ef.jpg)

The only thing I've changed is the angles and sizes of my hudplayerclass.res file.

**Comment by Duptier** [comment]
Actually, the meter might not be in the wrong position at all. However there is still text underneath the meter.

**Comment by Sevin7** [comment]
This is an unfortunate side effect of the vaccinator not having its own HUD file, it just renders over other elements.
