### ISSUE TITLE
[Question] How to bind skipping the map welcome

### ISSUE THREAD

**Issue by MaxOhNoo** [Sevin7/7hud#87]
![image](https://github.com/Sevin7/7hud/assets/87615947/44677330-d6c8-45b9-8627-acec935c7043)

Hey, could you show me what allows this hud to bind skipping the welcome screen to a key? This is super useful.

**Comment by Sevin7** [comment]
> 
> ![image](https://github.com/Sevin7/7hud/assets/87615947/44677330-d6c8-45b9-8627-acec935c7043)
> 
> Hey, could you show me what allows this hud to bind skipping the welcome screen to a key? This is super useful.

Adding "&" before a character in an element that has a command associated with it binds that character to the command. You can see this example resource/ui/mapinfo.res on line 89, where I bind "E" to the "continue" command on lines 89 and 93.

**Comment by MaxOhNoo** [comment]
Source spaghetti is truly magical, thx for the quick response!
